### ISSUE TITLE
create accordion component

### ISSUE THREAD

**Issue by struckchure** [struckchure/iwd#2]
Check the FAQ section [here](https://iwdindia.in/)

![Screenshot 2022-03-08 at 16-20-54 IWD India 2022](https://user-images.githubusercontent.com/55154055/157268461-ea92d420-530c-4d03-8e48-42462847f9ba.png)

**Comment by Horlakz** [comment]
na this small thing you create issue for
using typescript now huh

**Comment by Horlakz** [comment]
oya na

**Comment by struckchure** [comment]
opor fun @Horlakz

**Comment by mjay0100** [comment]
horlakz where u enter boss

**Comment by struckchure** [comment]
@mjay0100 

after series of refactoring, workflow later pass, we're on green now, your email inbox go don full already :laughing:

**Comment by mjay0100** [comment]
Lol lots of confusing emails 😂

**Comment by Horlakz** [comment]
omoo na one nonsense work waste my time this week
you guys have not done this thing now, why was it closed

**Comment by Horlakz** [comment]
> horlakz where u enter boss

i just wan shook hand inside sth wey no concern me ni

**Comment by struckchure** [comment]
I even think say na PR 🤦‍♂️
