### ISSUE TITLE
create profile card

### ISSUE THREAD

**Issue by struckchure** [struckchure/iwd#4]
![Screenshot 2022-03-08 at 19-07-28 IWD India 2022](https://user-images.githubusercontent.com/55154055/157299253-616b93c8-be22-462a-9f02-bcc0b90f64d3.png)

Make the card clickable and when it's clicked, a modal appears
![Screenshot 2022-03-08 at 19-08-29 IWD India 2022](https://user-images.githubusercontent.com/55154055/157299332-f81232d4-e01a-498d-9413-4b7f1d25947b.png)

**Comment by elijahthis** [comment]
> On it

**Comment by struckchure** [comment]
Done!

Good job @elijahthis
